### PR TITLE
update nmap scan

### PR DESCRIPTION
**Pull request by Hsmoy**
In the original function, each ip will perform a full scan on the scan to obtain the port, which will cause the scanning speed to be slow. I changed the scanning process to only scan the live port of the ip. Of course, this will cause problems with nmap output. Yes Add the --append-output parameter when calling through nmap, and the output content can be appended at this time. The above is google translation. English is not good, sorry

### CODE REVIEW

**Comment by Hsmoy** [comment]
We have to consider a problem. If one of the ip scans returns a large number of ports, such as 1-65535, due to the target firewall or other security policies, at this time, according to the original process, it will cause all the ip performs a lot of port scans. In this case, the scan will be extremely slow. And it will make the test target more aware of our behavior. Due to the process creation overhead, the repeated creation process will definitely be more than a single instance. Costs more. But I believe it's worth the wait time to cause a bigger noise than when testing the target.

**Comment by Hsmoy** [comment]
@Mzack9999   We have to consider a problem. If one of the ip scans returns a large number of ports, such as 1-65535, due to the target firewall or other security policies, at this time, according to the original process, it will cause all the ip performs a lot of port scans. In this case, the scan will be extremely slow. And it will make the test target more aware of our behavior. Due to the process creation overhead, the repeated creation process will definitely be more than a single instance. Costs more. But I believe it's worth the wait time to cause a bigger noise than when testing the target.

**Comment by Mzack9999** [comment]
@Hsmoy Thanks for giving more context around this issue. That's a use case where noisy results influence the total scan time. I opened a couple of issues to generalize the use case at https://github.com/projectdiscovery/naabu/issues/294 and https://github.com/projectdiscovery/naabu/issues/295 (in particular, this one should cover the problem highlighted in this PR, and hopefully still follow the nmap recommendations to minimize the number of running instances). Let me know if you think that anything is missing.

**Comment by Hsmoy** [comment]
@Mzack9999 I have an immature idea. In my experience of penetration testing, a specific host rarely opens a large number of ports. We can set a threshold for the number of ports, such as 100 to get others, and conduct a test on hosts that exceed the threshold. Verification scans usually only require 0-20 ports or others. If 0-20 ports are continuously open, it can be considered that this is a packet responded by a security device. Until now I have not seen such an open port host. This Just an immature idea.

**Pull request closed without merging**
