### PR TITLE
fix(rate): delete unnecessary usage of limit

### PR DESCRIPTION
**Pull request by akkuman**
r.limiter.Take() is used in bothr.RawSocketEnumeration and r.handleHostPort.
The use of Take() here will reduce our preset number of packets by half.

https://github.com/projectdiscovery/naabu/blob/master/v2/pkg/runner/runner.go#L439

https://github.com/projectdiscovery/naabu/blob/master/v2/pkg/runner/runner.go#L425

### CODE REVIEW

**Comment by ehsandeep** [comment]
@akkuman Could you recheck the code against dev branch?

**Review by Mzack9999 — APPROVED** [review]
@ehsandeep already rebased with `dev` (errors in test are expected due to increased coverage in race detection)

**Comment by akkuman** [comment]
@ehsandeep I had checked the dev branch, it has same problem

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
thank you flagging and pushing a fix for it @akkuman

**Pull request merged**
