### PR TITLE
Add support for integration and secondary development for #439

### PR DESCRIPTION
**Pull request by hktalent**
Add support for integration and secondary development for #439

### CODE REVIEW

**Comment by hktalent** [comment]
test code
```
package naabu

import (
	"fmt"
	"github.com/hktalent/ProScan4all/lib/util"
	_ "github.com/projectdiscovery/fdmax/autofdmax"
	"github.com/projectdiscovery/gologger"
	"github.com/projectdiscovery/naabu/v2/pkg/runner"
	"os"
)

func DoNaabu(target []string) {
	options := runner.ParseOptions(os.Args[1:]...)
	naabuRunner, err := runner.NewRunner(options)
	if err != nil {
		gologger.Fatal().Msgf("Could not create runner: %s\n", err)
	}
	naabuRunner.OutCbk = func(out ...interface{}) {
		fmt.Printf("test %+v", out)
	}
	util.RegCbk("exit", func() {
		naabuRunner.ShowScanResultOnExit()
		gologger.Info().Msgf("CTRL+C pressed: Exiting\n")
		if options.ResumeCfg.ShouldSaveResume() {
			gologger.Info().Msgf("Creating resume file: %s\n", runner.DefaultResumeFilePath())
			err := options.ResumeCfg.SaveResumeConfig()
			if err != nil {
				gologger.Error().Msgf("Couldn't create resume file: %s\n", err)
			}
		}
		naabuRunner.Close()
	})
	err = naabuRunner.RunEnumeration()
	if err != nil {
		gologger.Fatal().Msgf("Could not run enumeration: %s\n", err)
	}
	// on successful execution remove the resume file in case it exists
	options.ResumeCfg.CleanupResumeConfig()
}

```

**Comment by Mzack9999** [comment]
@hktalent unless I'm mistaken the `r.OutCbk` should be already equivalent to: https://github.com/projectdiscovery/naabu/blob/802d10a469eeba01d9837148187facec7c23c80a/v2/pkg/runner/options.go#L60

**Comment by hktalent** [comment]
But I searched this and it was not used
image

**Comment by hktalent** [comment]
yes i saw it
image

**Comment by Mzack9999** [comment]
@hktalent I think that all the options can be directly passed to the runner (see the [example](https://github.com/projectdiscovery/naabu/blob/main/v2/cmd/integration-test/library.go)). Are you facing any difficulty to integrate the tool or there is any particular logic in the `ParseOptions` function that you need to invoke as part of flags validation? Happy to implement required changes if that helps to make the integration easier.

**Comment by hktalent** [comment]
ok
Then close this PR

**Pull request closed without merging**
