### PR TITLE
Adding support for IP6

### PR DESCRIPTION
**Pull request by Mzack9999**
## Description
This PR adds support for IP6 to `naabu`

## Notes
Depends on:
- https://github.com/projectdiscovery/ipranger/pull/10
- https://github.com/projectdiscovery/mapcidr/pull/70

## Example
```console
$ echo fd00::xxxx:xxxx:xxxx:xxx | go run . -v -debug -p 15000
...
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host fd00::xxxx:xxxx:xxxx:xxx (fd00::xxxx:xxxx:xxxx:xxx)
fd00::xxxx:xxxx:xxxx:xxx:15000
$ echo fd00::xxxx:xxxx:xxxx:xxx | sudo go run . -v -debug -p 15000 -source-ip fd00::xxxx:xxxx:xxxx:xxx -interface en3
...
[DBG] Received TCP scan response from fd00::xxxx:xxxx:xxxx:xxx:15000
[DBG] Received TCP scan response from fd00::xxxx:xxxx:xxxx:xxx:15000
[DBG] Received TCP scan response from fd00::xxxx:xxxx:xxxx:xxx:15000
[INF] Found 1 ports on host fd00::xxxx:xxxx:xxxx:xxx (fd00::xxxx:xxxx:xxxx:xxx)
fd00::xxxx:xxxx:xxxx:xxx:15000
```

### CODE REVIEW

**Comment by sullo** [comment]
Have you worked out logic for ipv6 vs ipv4 when a hostname is provided as input? In nikto we ended up adding  `-ipv6` and `-ipv4` to force a choice if a name resolves with both (defaulting to ipv4).

**Comment by Mzack9999** [comment]
@sullo Good suggestion, actually we consider only ipv4. I'm going to add `-ipv6` and `-ipv4`

**Review by ehsandeep — COMMENTED** [review]
on MacOS, SYN scan is not working:

```console
$ echo '0000:0000:0000:0000:0000:ffff:c0a8:0101' | sudo ./naabu -p 443 -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.7

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running SYN scan with root privileges
[DBG] Discarding TCP packet from non target ips: ip4=192.168.1.1 ip6=<nil>
[DBG] Discarding TCP packet from non target ips: ip4=192.168.1.1 ip6=4ac5:b7f0:800:4500:2c:0:4000:4006
[DBG] Discarding TCP packet from non target ips: ip4=192.168.1.1 ip6=4ac5:b7f0:800:4500:28:19:4000:4006
````

```console
$ echo '0000:0000:0000:0000:0000:ffff:c0a8:0101' | ./naabu -p 443 -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.7

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running CONNECT scan with non root privileges
[INF] Found 1 ports on host 192.168.1.1 (192.168.1.1)
192.168.1.1:443
```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [ ] Invalid source IPv6 address with SYN Scan

```console
echo 2606:4700::6810:6334 | sudo ./naabu -p 80 -debug -i en0 -v

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.7

    projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running SYN scan with root privileges
[DBG] Can not send packet to 2606:4700::6810:6334:80 port: Invalid source IPv6 address (address is IPv4)
[DBG] Can not send packet to 2606:4700::6810:6334:80 port: Invalid source IPv6 address (address is IPv4)
[DBG] Can not send packet to 2606:4700::6810:6334:80 port: Invalid source IPv6 address (address is IPv4)
```

- [x] Readme update for IPv6 support network prerequisite
- [x] Git merge conflict

**Pull request merged**
