### PR TITLE
⬆️ update to current versions of some actions

### PR DESCRIPTION
**Pull request by thomasmerz**

### CODE REVIEW

**Comment by thomasmerz** [comment]
I read about your little tool in [german "Linux User" on page 8](https://www.linux-community.de/wp-content/uploads/2024/11/lu-ce_2024-11.pdf) 😃 and I wanted to use it, but I had to do some fixes to make it work (as GitHub Action)…

**Review by dogancanbakir — APPROVED** [review]

**Review by Mzack9999 — COMMENTED** [review]
@thomasmerz Thanks for the PR! Various GH actions should be already updated in the `dev` branch which contains all the latest developments, they are just not released in the main branch yet.
Before bumping the go version could you share more insights about why go 1.21 is not working in GH actions?

**Comment by thomasmerz** [comment]
> Before bumping the go version could you share more insights about why go 1.21 is not working in GH actions?

GH actions also works with `go 1.21` - but I thought it might be ok to also use a more current minor version that doesn't break anything. See my test-run in my private sandbox-repo for testing:

image

Is it ok for you to also update go version or should I revert to 1.21.x?

**Comment by ehsandeep** [comment]
@thomasmerz, we can revert this to 1.21.x. We have multiple projects using each other as dependency projects, so we’re looking to stick to a specific version unless a feature requires an update for implementation in the tool.

**Comment by thomasmerz** [comment]
@ehsandeep , I reverted go version to 1.21.x.

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
